import { CandidateProfile } from '../contracts/CandidateProfile/interfaces'; // Adjust the path as necessary

export const candidatesData: CandidateProfile[] = [
  {
    key: '1',
    name: 'MAHNOOR SAFEER ABBASI',
    aggregatedScore: 4.96,
    email: 'mahnoorsafeer421@gmail.com',
    phone: '+92-333-0562380',
    currentPosition: 'Data Science Intern',
    currentCompany: 'Stella Technology',
    totalExperience: 1.18,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '6-2023',
    location: 'Karachi, Pakistan',
    skills: ['Python', 'Data Analysis', 'Machine Learning'],
    certifications: ['AWS Certified Solutions Architect', 'Certified Data Scientist'],
    education: 'Bachelor of Science in Computer Science',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/mahnoor-safeer-abbasi/',
    githubProfile: 'https://github.com/mahnoor-safeer',
    portfolio: 'https://mahnoorsafeer.com/',
    availability: '2 weeks',
    expectedSalary: 'PKR 150,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed a machine learning model for predictive analysis', 'Led a team in building a SaaS platform'],
    summary: 'Experienced Data Scientist with a strong background in machine learning and predictive analytics.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '2',
    name: 'Ehtesham Safeer',
    aggregatedScore: 4.92,
    email: 'ehteshamrajpoot01@gmail.com',
    phone: '03135833852',
    currentPosition: 'AI Developer Intern',
    currentCompany: 'Octaloop Technologies',
    totalExperience: 1.01,
    experienceWithCurrentCompany: 1,
    employmentStartDate: '2023-08',
    location: 'Lahore, Pakistan',
    skills: ['JavaScript', 'AI Development', 'React'],
    certifications: ['Certified AI Developer', 'React Professional'],
    education: 'Bachelor of Science in Software Engineering',
    languages: ['English', 'Punjabi'],
    linkedinProfile: 'https://www.linkedin.com/in/ehtesham-safeer/',
    githubProfile: 'https://github.com/ehtesham-safeer',
    portfolio: 'https://ehtesham-safeer.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 120,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed an AI-based chatbot', 'Created a real-time data visualization tool using React'],
    summary: 'AI Developer with a passion for building intelligent systems and a solid foundation in software engineering.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '3',
    name: 'John Doe',
    aggregatedScore: 4.85,
    email: 'johndoe@example.com',
    phone: '+92-123-4567890',
    currentPosition: 'Software Engineer',
    currentCompany: 'Tech Solutions',
    totalExperience: 2.5,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2019-04',
    location: 'Islamabad, Pakistan',
    skills: ['C++', 'Java', 'Software Architecture'],
    certifications: ['Certified Software Architect'],
    education: 'Master of Science in Computer Science',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/johndoe/',
    githubProfile: 'https://github.com/johndoe',
    portfolio: 'https://johndoe.com/',
    availability: '1 month',
    expectedSalary: 'PKR 180,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Designed and implemented a large-scale enterprise software solution', 'Led a team in migrating legacy systems to microservices architecture'],
    summary: 'Software Engineer with expertise in building scalable software solutions and a track record of leading successful projects.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '4',
    name: 'Jane Smith',
    aggregatedScore: 4.75,
    email: 'janesmith@example.com',
    phone: '+92-987-6543210',
    currentPosition: 'Product Manager',
    currentCompany: 'Innovate Inc.',
    totalExperience: 3.8,
    experienceWithCurrentCompany: 3,
    employmentStartDate: '2018-01',
    location: 'Karachi, Pakistan',
    skills: ['Product Management', 'Agile Methodologies', 'User Research'],
    certifications: ['Certified Scrum Master', 'Certified Product Manager'],
    education: 'Bachelor of Business Administration',
    languages: ['English', 'Sindhi'],
    linkedinProfile: 'https://www.linkedin.com/in/janesmith/',
    githubProfile: '',
    portfolio: 'https://janesmith.com/',
    availability: '3 months',
    expectedSalary: 'PKR 250,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Successfully launched a new product line that increased company revenue by 20%', 'Led a cross-functional team in transitioning to Agile methodology'],
    summary: 'Product Manager with extensive experience in leading product development from concept to launch, and a deep understanding of user needs.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '5',
    name: 'Alice Johnson',
    aggregatedScore: 4.65,
    email: 'alicejohnson@example.com',
    phone: '+92-555-1234567',
    currentPosition: 'UX Designer',
    currentCompany: 'Creative Minds',
    totalExperience: 1.5,
    experienceWithCurrentCompany: 1,
    employmentStartDate: '2020-07',
    location: 'Lahore, Pakistan',
    skills: ['UX Design', 'Adobe XD', 'User Testing'],
    certifications: ['Certified UX Designer'],
    education: 'Bachelor of Arts in Graphic Design',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/alicejohnson/',
    githubProfile: '',
    portfolio: 'https://alicejohnson.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 100,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Redesigned the user interface for a major e-commerce platform, improving user satisfaction by 30%', 'Conducted extensive user research and testing for a mobile app development project'],
    summary: 'UX Designer with a passion for creating user-friendly interfaces and a strong background in graphic design.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '6',
    name: 'Bob Brown',
    aggregatedScore: 4.55,
    email: 'bobbrown@example.com',
    phone: '+92-444-7654321',
    currentPosition: 'Marketing Specialist',
    currentCompany: 'Market Leaders',
    totalExperience: 2.2,
    experienceWithCurrentCompany: 1.5,
    employmentStartDate: '2021-03',
    location: 'Islamabad, Pakistan',
    skills: ['Digital Marketing', 'SEO', 'Content Strategy'],
    certifications: ['Google Ads Certified', 'Certified Digital Marketing Professional'],
    education: 'Bachelor of Business Administration in Marketing',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/bobbrown/',
    githubProfile: '',
    portfolio: 'https://bobbrown.com/',
    availability: '2 weeks',
    expectedSalary: 'PKR 140,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed and implemented a content strategy that boosted organic traffic by 40%', 'Managed multiple successful digital marketing campaigns for a variety of clients'],
    summary: 'Marketing Specialist with a focus on digital marketing and content strategy, and a proven track record of driving business growth.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '7',
    name: 'Charlie Davis',
    aggregatedScore: 4.50,
    email: 'charliedavis@example.com',
    phone: '+92-333-9876543',
    currentPosition: 'Data Analyst',
    currentCompany: 'Data Insights',
    totalExperience: 2.0,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2021-06',
    location: 'Karachi, Pakistan',
    skills: ['Data Analysis', 'SQL', 'Tableau'],
    certifications: ['Certified Data Analyst', 'Tableau Desktop Specialist'],
    education: 'Bachelor of Science in Statistics',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/charliedavis/',
    githubProfile: '',
    portfolio: 'https://charliedavis.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 130,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Conducted data analysis for a major retail company, identifying key trends and insights', 'Developed dashboards and reports for senior management using Tableau'],
    summary: 'Data Analyst with strong analytical skills and experience in data visualization, committed to helping organizations make data-driven decisions.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '8',
    name: 'David Wilson',
    aggregatedScore: 4.40,
    email: 'davidwilson@example.com',
    phone: '+92-222-4567890',
    currentPosition: 'HR Manager',
    currentCompany: 'People First',
    totalExperience: 3.0,
    experienceWithCurrentCompany: 2.5,
    employmentStartDate: '2019-09',
    location: 'Lahore, Pakistan',
    skills: ['Human Resources', 'Recruitment', 'Employee Relations'],
    certifications: ['Certified HR Professional'],
    education: 'Master of Business Administration in Human Resource Management',
    languages: ['English', 'Punjabi'],
    linkedinProfile: 'https://www.linkedin.com/in/davidwilson/',
    githubProfile: '',
    portfolio: '',
    availability: '1 month',
    expectedSalary: 'PKR 200,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Implemented a new employee engagement program that reduced turnover by 15%', 'Led a successful recruitment campaign for a rapidly growing tech company'],
    summary: 'HR Manager with a strong background in employee relations and recruitment, dedicated to fostering a positive workplace culture.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '9',
    name: 'Emma Thomas',
    aggregatedScore: 4.35,
    email: 'emmathomas@example.com',
    phone: '+92-111-1234567',
    currentPosition: 'Business Analyst',
    currentCompany: 'Business Solutions',
    totalExperience: 1.8,
    experienceWithCurrentCompany: 1,
    employmentStartDate: '2022-02',
    location: 'Islamabad, Pakistan',
    skills: ['Business Analysis', 'Process Improvement', 'Agile Methodologies'],
    certifications: ['Certified Business Analyst Professional'],
    education: 'Bachelor of Business Administration',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/emmathomas/',
    githubProfile: '',
    portfolio: '',
    availability: 'Immediate',
    expectedSalary: 'PKR 150,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Analyzed business processes for a major client, identifying areas for improvement', 'Worked with cross-functional teams to implement process changes'],
    summary: 'Business Analyst with experience in process improvement and a solid understanding of Agile methodologies, focused on delivering value to clients.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '10',
    name: 'Frank Martin',
    aggregatedScore: 4.30,
    email: 'frankmartin@example.com',
    phone: '+92-999-6543210',
    currentPosition: 'IT Consultant',
    currentCompany: 'ConsultTech',
    totalExperience: 2.7,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2020-10',
    location: 'Karachi, Pakistan',
    skills: ['IT Consulting', 'Cloud Computing', 'Cybersecurity'],
    certifications: ['Certified Information Systems Security Professional (CISSP)', 'AWS Certified Solutions Architect'],
    education: 'Bachelor of Science in Information Technology',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/frankmartin/',
    githubProfile: '',
    portfolio: 'https://frankmartin.com/',
    availability: '2 months',
    expectedSalary: 'PKR 220,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Provided IT consulting services for a Fortune 500 company, resulting in significant cost savings', 'Led a cloud migration project for a mid-sized enterprise, improving scalability and security'],
    summary: 'IT Consultant with expertise in cloud computing and cybersecurity, helping businesses to optimize their IT infrastructure.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '11',
    name: 'Grace Lee',
    aggregatedScore: 4.25,
    email: 'gracelee@example.com',
    phone: '+92-888-9876543',
    currentPosition: 'Operations Manager',
    currentCompany: 'Efficient Ops',
    totalExperience: 3.5,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2018-11',
    location: 'Lahore, Pakistan',
    skills: ['Operations Management', 'Supply Chain Management', 'Lean Six Sigma'],
    certifications: ['Lean Six Sigma Black Belt'],
    education: 'Master of Business Administration',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/gracelee/',
    githubProfile: '',
    portfolio: '',
    availability: '3 months',
    expectedSalary: 'PKR 230,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Led a supply chain optimization project that reduced costs by 10%', 'Implemented Lean Six Sigma methodologies to improve operational efficiency'],
    summary: 'Operations Manager with a proven track record in optimizing business operations and driving efficiency improvements.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '12',
    name: 'Hannah Scott',
    aggregatedScore: 4.20,
    email: 'hannahscott@example.com',
    phone: '+92-777-4567890',
    currentPosition: 'Financial Analyst',
    currentCompany: 'Finance Experts',
    totalExperience: 2.3,
    experienceWithCurrentCompany: 1.8,
    employmentStartDate: '2019-05',
    location: 'Islamabad, Pakistan',
    skills: ['Financial Analysis', 'Excel Modeling', 'Risk Management'],
    certifications: ['Chartered Financial Analyst (CFA) Level 2'],
    education: 'Bachelor of Commerce',
    languages: ['English', 'Punjabi'],
    linkedinProfile: 'https://www.linkedin.com/in/hannahscott/',
    githubProfile: '',
    portfolio: '',
    availability: '1 month',
    expectedSalary: 'PKR 180,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed financial models for a major investment firm, supporting key investment decisions', 'Conducted risk assessments for a portfolio of high-value clients'],
    summary: 'Financial Analyst with expertise in financial modeling and risk management, committed to delivering accurate and actionable insights.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '13',
    name: 'Ian Roberts',
    aggregatedScore: 4.15,
    email: 'ianroberts@example.com',
    phone: '+92-666-1234567',
    currentPosition: 'Legal Advisor',
    currentCompany: 'Law Solutions',
    totalExperience: 3.2,
    experienceWithCurrentCompany: 3,
    employmentStartDate: '2017-12',
    location: 'Karachi, Pakistan',
    skills: ['Legal Consulting', 'Contract Law', 'Compliance'],
    certifications: ['Licensed Attorney at Law'],
    education: 'Bachelor of Laws (LLB)',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/ianroberts/',
    githubProfile: '',
    portfolio: '',
    availability: '2 months',
    expectedSalary: 'PKR 250,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Provided legal counsel to a multinational corporation, ensuring compliance with local and international regulations', 'Drafted and reviewed contracts for a wide range of clients across various industries'],
    summary: 'Legal Advisor with extensive experience in contract law and compliance, dedicated to providing sound legal advice to clients.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '14',
    name: 'Jack Adams',
    aggregatedScore: 4.10,
    email: 'jackadams@example.com',
    phone: '+92-555-9876543',
    currentPosition: 'Research Scientist',
    currentCompany: 'Innovate Labs',
    totalExperience: 4.0,
    experienceWithCurrentCompany: 2.5,
    employmentStartDate: '2018-08',
    location: 'Islamabad, Pakistan',
    skills: ['Research', 'Data Science', 'Machine Learning'],
    certifications: ['PhD in Computer Science'],
    education: 'Doctor of Philosophy (PhD) in Computer Science',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/jackadams/',
    githubProfile: 'https://github.com/jackadams',
    portfolio: 'https://jackadams.com/',
    availability: '3 months',
    expectedSalary: 'PKR 300,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Led a research project on artificial intelligence that resulted in a publication in a top-tier journal', 'Developed a novel machine learning algorithm that improved prediction accuracy by 15%'],
    summary: 'Research Scientist with a strong background in AI and data science, committed to pushing the boundaries of technology through innovative research.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '15',
    name: 'Karen Turner',
    aggregatedScore: 1.05,
    email: 'karenturner@example.com',
    phone: '+92-444-7654321',
    currentPosition: 'Customer Support Lead',
    currentCompany: 'Support Solutions',
    totalExperience: 1.7,
    experienceWithCurrentCompany: 1,
    employmentStartDate: '2021-01',
    location: 'Karachi, Pakistan',
    skills: ['Customer Support', 'Team Management', 'CRM'],
    certifications: ['Certified Customer Service Professional'],
    education: 'Bachelor of Arts in Communication',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/karenturner/',
    githubProfile: '',
    portfolio: '',
    availability: '1 month',
    expectedSalary: 'PKR 110,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Managed a customer support team for a growing tech company, improving response times by 20%', 'Implemented a new CRM system that streamlined customer interactions'],
    summary: 'Customer Support Lead with experience in managing support teams and implementing effective customer service strategies, focused on delivering exceptional customer experiences.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '16',
    name: 'Liam White',
    aggregatedScore: 2.95,
    email: 'liamwhite@example.com',
    phone: '+92-123-9876543',
    currentPosition: 'Frontend Developer',
    currentCompany: 'WebWorks',
    totalExperience: 3.0,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2019-08',
    location: 'Lahore, Pakistan',
    skills: ['JavaScript', 'React', 'CSS'],
    certifications: ['Certified Frontend Developer'],
    education: 'Bachelor of Science in Computer Science',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/liamwhite/',
    githubProfile: 'https://github.com/liamwhite',
    portfolio: 'https://liamwhite.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 160,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed responsive web applications for various clients', 'Implemented complex UI components with React'],
    summary: 'Frontend Developer with a strong foundation in JavaScript and React, dedicated to building user-friendly web applications.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '17',
    name: 'Noah Brown',
    aggregatedScore: 3.85,
    email: 'noahbrown@example.com',
    phone: '+92-333-7654321',
    currentPosition: 'Backend Developer',
    currentCompany: 'CodeCraft',
    totalExperience: 3.5,
    experienceWithCurrentCompany: 1.5,
    employmentStartDate: '2021-03',
    location: 'Islamabad, Pakistan',
    skills: ['Node.js', 'Express', 'MongoDB'],
    certifications: ['Certified Backend Developer'],
    education: 'Bachelor of Science in Software Engineering',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/noahbrown/',
    githubProfile: 'https://github.com/noahbrown',
    portfolio: 'https://noahbrown.com/',
    availability: '2 weeks',
    expectedSalary: 'PKR 180,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed RESTful APIs for various applications', 'Integrated third-party services into backend systems'],
    summary: 'Backend Developer with expertise in Node.js and database management, focused on building scalable and efficient server-side applications.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '18',
    name: 'Sophia Khan',
    aggregatedScore: 3.75,
    email: 'sophiakhan@example.com',
    phone: '+92-999-8765432',
    currentPosition: 'Project Manager',
    currentCompany: 'Tech Innovators',
    totalExperience: 5.0,
    experienceWithCurrentCompany: 3,
    employmentStartDate: '2018-02',
    location: 'Karachi, Pakistan',
    skills: ['Project Management', 'Agile', 'Scrum'],
    certifications: ['Certified Scrum Master', 'PMP'],
    education: 'Master of Business Administration',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/sophiakhan/',
    githubProfile: '',
    portfolio: '',
    availability: '1 month',
    expectedSalary: 'PKR 240,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Led multiple software development projects using Agile methodologies', 'Implemented project management tools and best practices'],
    summary: 'Project Manager with extensive experience in Agile methodologies, dedicated to delivering projects on time and within budget.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '19',
    name: 'Olivia Ali',
    aggregatedScore: 2.65,
    email: 'oliviaali@example.com',
    phone: '+92-888-6543210',
    currentPosition: 'Content Writer',
    currentCompany: 'Creative Content',
    totalExperience: 2.0,
    experienceWithCurrentCompany: 1,
    employmentStartDate: '2022-01',
    location: 'Islamabad, Pakistan',
    skills: ['Content Writing', 'SEO', 'Copywriting'],
    certifications: ['Certified Content Strategist'],
    education: 'Bachelor of Arts in English Literature',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/oliviaali/',
    githubProfile: '',
    portfolio: 'https://oliviaali.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 90,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Created content strategies that increased organic traffic', 'Wrote and edited content for various platforms'],
    summary: 'Content Writer with a passion for storytelling and a strong understanding of SEO, committed to creating engaging and impactful content.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '20',
    name: 'William Hasan',
    aggregatedScore: 3.55,
    email: 'williamhasan@example.com',
    phone: '+92-777-1234567',
    currentPosition: 'Graphic Designer',
    currentCompany: 'Design Studio',
    totalExperience: 3.0,
    experienceWithCurrentCompany: 1.5,
    employmentStartDate: '2021-06',
    location: 'Lahore, Pakistan',
    skills: ['Graphic Design', 'Adobe Illustrator', 'Photoshop'],
    certifications: ['Certified Graphic Designer'],
    education: 'Bachelor of Arts in Graphic Design',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/williamhasan/',
    githubProfile: '',
    portfolio: 'https://williamhasan.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 110,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Designed logos and branding materials for various clients', 'Developed marketing materials that boosted client engagement'],
    summary: 'Graphic Designer with a strong creative flair and experience in creating visually appealing designs for various mediums.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '21',
    name: 'James Rizvi',
    aggregatedScore: 3.45,
    email: 'jamesrizvi@example.com',
    phone: '+92-666-9876543',
    currentPosition: 'Full Stack Developer',
    currentCompany: 'Tech Solutions',
    totalExperience: 4.0,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2019-04',
    location: 'Karachi, Pakistan',
    skills: ['JavaScript', 'Node.js', 'React'],
    certifications: ['Certified Full Stack Developer'],
    education: 'Bachelor of Science in Computer Science',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/jamesrizvi/',
    githubProfile: 'https://github.com/jamesrizvi',
    portfolio: 'https://jamesrizvi.com/',
    availability: '1 month',
    expectedSalary: 'PKR 180,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed full-stack web applications for various industries', 'Integrated APIs and third-party services into web applications'],
    summary: 'Full Stack Developer with expertise in JavaScript and a proven track record of delivering robust web applications.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '22',
    name: 'Isabella Malik',
    aggregatedScore: 3.35,
    email: 'isabellamalik@example.com',
    phone: '+92-555-7654321',
    currentPosition: 'Business Development Manager',
    currentCompany: 'Growth Strategies',
    totalExperience: 5.5,
    experienceWithCurrentCompany: 3,
    employmentStartDate: '2018-05',
    location: 'Islamabad, Pakistan',
    skills: ['Business Development', 'Sales', 'Client Relations'],
    certifications: ['Certified Business Development Professional'],
    education: 'Master of Business Administration',
    languages: ['English', 'Punjabi'],
    linkedinProfile: 'https://www.linkedin.com/in/isabellamalik/',
    githubProfile: '',
    portfolio: '',
    availability: 'Immediate',
    expectedSalary: 'PKR 280,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Led business development initiatives that resulted in a 25% increase in revenue', 'Established and maintained key client relationships'],
    summary: 'Business Development Manager with a focus on driving revenue growth and building strong client relationships.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '23',
    name: 'Lucas Shah',
    aggregatedScore: 3.25,
    email: 'lucasshah@example.com',
    phone: '+92-444-1234567',
    currentPosition: 'DevOps Engineer',
    currentCompany: 'CloudTech',
    totalExperience: 4.5,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2020-01',
    location: 'Lahore, Pakistan',
    skills: ['DevOps', 'AWS', 'Docker'],
    certifications: ['Certified DevOps Engineer'],
    education: 'Bachelor of Science in Information Technology',
    languages: ['English', 'Urdu'],
    linkedinProfile: 'https://www.linkedin.com/in/lucasshah/',
    githubProfile: 'https://github.com/lucasshah',
    portfolio: 'https://lucasshah.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 200,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Implemented CI/CD pipelines for various projects', 'Managed cloud infrastructure on AWS, ensuring high availability and security'],
    summary: 'DevOps Engineer with a strong background in cloud technologies and experience in automating deployment processes.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '24',
    name: 'Mia Ahmed',
    aggregatedScore: 3.15,
    email: 'miaahmed@example.com',
    phone: '+92-333-8765432',
    currentPosition: 'UI/UX Designer',
    currentCompany: 'DesignHub',
    totalExperience: 2.5,
    experienceWithCurrentCompany: 1.5,
    employmentStartDate: '2021-04',
    location: 'Karachi, Pakistan',
    skills: ['UI/UX Design', 'Figma', 'User Research'],
    certifications: ['Certified UI/UX Designer'],
    education: 'Bachelor of Arts in Graphic Design',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/miaahmed/',
    githubProfile: '',
    portfolio: 'https://miaahmed.com/',
    availability: 'Immediate',
    expectedSalary: 'PKR 120,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Redesigned mobile app interfaces for improved usability', 'Conducted user research to inform design decisions'],
    summary: 'UI/UX Designer with a passion for creating intuitive user experiences and a strong background in graphic design.',
    lastUpdated: '2023-10-05'
  },
  {
    key: '25',
    name: 'Amelia Khan',
    aggregatedScore: 3.05,
    email: 'ameliakhan@example.com',
    phone: '+92-222-6543210',
    currentPosition: 'QA Engineer',
    currentCompany: 'TestPro',
    totalExperience: 3.0,
    experienceWithCurrentCompany: 2,
    employmentStartDate: '2021-02',
    location: 'Islamabad, Pakistan',
    skills: ['Quality Assurance', 'Automation Testing', 'Selenium'],
    certifications: ['Certified QA Engineer'],
    education: 'Bachelor of Science in Computer Science',
    languages: ['English'],
    linkedinProfile: 'https://www.linkedin.com/in/ameliakhan/',
    githubProfile: '',
    portfolio: '',
    availability: '2 weeks',
    expectedSalary: 'PKR 150,000 per month',
    references: 'Available upon request',
    workAuthorization: 'Yes',
    projects: ['Developed automated test scripts for web applications', 'Collaborated with development teams to identify and resolve software defects'],
    summary: 'QA Engineer with experience in manual and automated testing, focused on ensuring the quality and reliability of software products.',
    lastUpdated: '2023-10-05'
  }
];
